# Generated by Django 6.0 on 2025-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('s3_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('language', models.CharField(default='pt-BR', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
